### PR TITLE
Make azure cloud instance configurable

### PR DESCRIPTION
**Pull request by sputnik13**
AD Auth and kusto resource/context URLs differ depending on which Azure
cloud is being used (global Azure vs sovereign/national clouds), but the
use of a hardcoded AD and kusto resource endpoint prevent the plugin
from working in these environments.  Added two separate configuration
items for AD Auth endpoint and kusto resource/context URL to allow these
to be set to the appropriate value for the Azure cloud being used.

### CODE REVIEW

**Comment by sputnik13** [comment]
This also addresses #16 

Allowing the URLs and paths to be configurable would also allow the plugin to be used in future instances without needing explicit updates, but it is obviously a little less user friendly than having a dropdown list to choose from.

**Comment by djj0809** [comment]
@shavonn @srclosson could you have a look at this, it's a really simple PR and it will help us a lot, thanks!

**Comment by sputnik13** [comment]
@srclosson @briangann the PR has been open for quite a while now, anything that can be done to help it along?

**Comment by djj0809** [comment]
Ping

**Comment by andresmgot** [comment]
Is this PR still relevant? Can you fix the conflicts?

**Comment by andresmgot** [comment]
Closing due to inactivity

**Pull request closed without merging**
