### PR TITLE
National cloud scope fix

### PR DESCRIPTION
**Pull request by sunker**

### CODE REVIEW

**Comment by sunker** [comment]
@floushee regarding: https://github.com/grafana/azure-data-explorer-datasource/pull/250

Still haven't gotten an answer for MSFT yet. If I don't get an answer soon, I'm tempted to merge your national clouds fix anyway. A few things has changed in the master branch lately, so had to make some adjustments to your fix. Does it look okay to you? If you want your name on the PR, you can cherry-pick this commit into your PR and force push.

**Comment by floushee** [comment]
Hi @sunker . Just go ahead. No need for me to have my name attached to it. I would be just happy if I can stop using my custom build and switch to the official one :)

**Comment by jci-zimm** [comment]
Can we please merge this? Without this, china ADE data sources don't work (unless i'm missing something). I manually built & tested this PR with a china ADE data source and it worked.

**Comment by andresmgot** [comment]
Let's merge this, I don't see a reason for not doing it

**Comment by floushee** [comment]
That's awesome!

**Comment by jci-zimm** [comment]
Many thanks for merging, any chance we can get a release with this in it?

**Comment by andresmgot** [comment]
Just released this: https://github.com/grafana/azure-data-explorer-datasource/releases/tag/v3.7.1

**Comment by jci-zimm** [comment]
Many thanks, its working great!

**Pull request merged**
