### PR TITLE
Add Playwright and k6 E2E tests for comparison

### PR DESCRIPTION
**Pull request by adamyeats**

### CODE REVIEW

**Review by aangelisc — APPROVED** [review]
Great work on this!

**Review by aangelisc — APPROVED** [review]
LGTM 😊 great stuff! Are all of the changes in `cspell.config.json` needed? There are some duplicates in there

**Comment by adamyeats** [comment]
> LGTM 😊 great stuff! Are all of the changes in `cspell.config.json` needed? There are some duplicates in there

Thanks for pointing this out, I've removed the duplicates! I sorted those lines alphabetically which made the duplicates easy to spot, so I would say that the change is worth keeping IMO

**Review by aangelisc — APPROVED** [review]

**Review by alyssabull — DISMISSED** [review]
LGTM - amazing work! 💪

**Review by aangelisc — APPROVED** [review]

**Pull request merged**
