### PR TITLE
Refactor: Fixes so backspace removes selected value

### PR DESCRIPTION
**Pull request by hugohaggmark**

### CODE REVIEW

**Comment by mckn** [comment]
I think this works great! It would be even better if you could make it select the "previously selected" if you clear but do not select anything new (as in the gif). Maybe timebox and see if it is possible to get in place?

**Comment by mckn** [comment]
Kapture 2020-09-22 at 07 41 48

**Comment by hugohaggmark** [comment]
Will have a quick look, will probably introduce ugly hack :)

**Comment by hugohaggmark** [comment]
Just a heads up the gif animation is for selects that I haven't changed.
https://github.com/grafana/azure-data-explorer-datasource/pull/147#issuecomment-696519240

**Comment by hugohaggmark** [comment]
@mckn please have another look, this is just woking for QueryEditorField right now

**Comment by mckn** [comment]
> @mckn please have another look, this is just woking for QueryEditorField right now

This is spot on! Awesome, we should probably add this for the operator value field as well.

**Review by mckn — APPROVED** [review]
LGTM!

**Pull request merged**
